/-
  Generated by `scripts/build-lean.ts` from the registry. Do not edit.
  Registry 2026.08.3, schema 1.2.0.
-/
import Hoba.Machine

namespace Hoba

/-- WF-003, the canonical path: the process as the commitments it is supposed to keep. -/
def ideal : Machine where
  n := 15
  kind := [Kind.initial, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.terminal, Kind.terminal, Kind.terminal]
  deviations := [[64, 45, 66], [81, 77, 46, 56, 65, 20], [69, 43], [70, 48, 51, 60], [75, 49], [79, 44, 54, 57], [84, 82, 41, 50, 59, 63], [74, 83, 71, 42, 52, 53, 55, 58, 62], [72, 44], [73, 47], [76, 47], [80, 78, 61, 67, 68, 19], [], [1, 7, 12, 13], [0, 2, 10, 11, 46, 60]]
  edges := [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10), (10, 11), (11, 12), (4, 13), (5, 13), (6, 13), (7, 13), (8, 13), (11, 13), (1, 14), (9, 14), (10, 14)]
  rank := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 11]

/-- State names for `ideal`, in index order. -/
def idealNames : List String := ["real-need", "published", "applied", "machine-check", "human-read", "terms-check", "work-sample", "panel", "level-and-band", "approval", "offer", "verification", "hired", "declined", "closed"]

/-- WF-001, the funnel as it actually runs. -/
def observed : Machine where
  n := 17
  kind := [Kind.initial, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.terminal, Kind.terminal, Kind.terminal, Kind.terminal]
  deviations := [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
  edges := [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (4, 14), (5, 6), (5, 16), (6, 7), (6, 14), (7, 8), (7, 14), (8, 9), (8, 14), (9, 10), (9, 14), (10, 11), (10, 15), (11, 12), (11, 15), (12, 13), (12, 14), (2, 16), (14, 2)]
  rank := [0, 1, 206, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 205, 204, 198]

/-- State names for `observed`, in index order. -/
def observedNames : List String := ["drafted", "authorised", "published", "received", "machine-screened", "recruiter-queue", "recruiter-screen", "technical", "panel", "levelling", "approval", "offer", "verification", "hired", "rejected", "frozen", "lapsed"]

/-- The barrier DAG, ordered by funnel position. -/
def gates : Machine where
  n := 16
  kind := [Kind.initial, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.terminal, Kind.terminal, Kind.terminal]
  deviations := [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
  edges := [(0, 1), (0, 2), (1, 2), (1, 5), (2, 3), (3, 4), (3, 5), (4, 5), (5, 6), (6, 7), (6, 8), (7, 8), (8, 9), (9, 10), (10, 11), (11, 12), (12, 13)]
  rank := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 0]

/-- State names for `gates`, in index order. -/
def gatesNames : List String := ["bar.requisition_approval_public_posting", "bar.outbound_sourcing_talent_pool_contact", "bar.application_ingestion", "bar.automated_filter_parser_threshold", "bar.inbound_screening_triage", "bar.recruiter_screening_call", "bar.technical_screen_live_assessment", "bar.take_home_work_sample_evaluation", "bar.hiring_manager_in_depth_review", "bar.team_cross_functional_panel", "bar.compensation_levelling_reconciliation", "bar.headcount_executive_budget_approval", "bar.reference_background_verification", "bar.offer_closing_contract_execution", "bar.client_profile_approval_and_client_interview", "bar.probation_period_post_start_confirmation"]

/-- Every entity a state can name, in index order. -/
def entityNames : List String := ["A-001", "A-002", "A-003", "A-004", "A-005", "A-006", "A-007", "A-008", "A-009", "A-010", "A-011", "A-012", "A-013", "A-014", "A-015", "A-016", "A-017", "A-018", "A-019", "A-020", "A-021", "I-001", "I-002", "I-003", "I-004", "I-005", "I-006", "I-007", "I-008", "I-009", "I-010", "I-011", "I-012", "I-013", "I-014", "I-015", "I-016", "I-017", "L-001", "L-002", "L-003", "M-001", "M-002", "M-003", "M-004", "M-005", "M-006", "M-007", "M-008", "M-009", "M-010", "M-011", "M-012", "M-013", "M-014", "M-015", "M-016", "M-017", "M-018", "M-019", "M-020", "M-021", "M-022", "M-023", "M-024", "M-025", "M-026", "M-027", "M-028", "bar.application_ingestion", "bar.automated_filter_parser_threshold", "bar.client_profile_approval_and_client_interview", "bar.compensation_levelling_reconciliation", "bar.headcount_executive_budget_approval", "bar.hiring_manager_in_depth_review", "bar.inbound_screening_triage", "bar.offer_closing_contract_execution", "bar.outbound_sourcing_talent_pool_contact", "bar.probation_period_post_start_confirmation", "bar.recruiter_screening_call", "bar.reference_background_verification", "bar.requisition_approval_public_posting", "bar.take_home_work_sample_evaluation", "bar.team_cross_functional_panel", "bar.technical_screen_live_assessment", "pat.closed_then_reposted_requisition_motif", "pat.compensation_double_bind", "pat.experience_age_impossibility", "pat.seniority_double_bind"]

/-- The barriers, as indices into `entityNames`. -/
def barrierIds : List Nat := [69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84]

/-- The mechanisms, as indices into `entityNames`. -/
def mechanismIds : List Nat := [41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]

/-- A closed walk found in the observed funnel: out of this state, and back. -/
def observedCycleStart : Nat := 2
def observedCycleTail : List Nat := [3, 4, 14]

/-- Substrate summary: conditions, processes, records, and event classes. -/
def substrateSummary : SubstrateSummary where
  conditionCount := 44
  processCount := 4
  recordCount := 97
  flowCount := 9
  barrierConditionCount := 16
  mechanismConditionCount := 28
  eventClassCount := 75

end Hoba
