/-
  Generated by `scripts/build-lean.ts` from the registry. Do not edit.
  Registry 2026.08.2, schema 1.1.0.
-/
import Hoba.Machine

namespace Hoba

/-- WF-003, the canonical path: the process as the commitments it is supposed to keep. -/
def ideal : Machine where
  n := 15
  kind := [Kind.initial, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.terminal, Kind.terminal, Kind.terminal]
  deviations := [[75, 56], [30, 31, 57, 67], [18, 54], [19, 59, 62, 71], [20, 60], [21, 55, 65, 68], [22, 23, 52, 61, 70, 74], [24, 25, 53, 63, 64, 66, 69, 73], [26, 55], [27, 58], [29, 58], [28, 72], [], [1, 7, 12, 13], [0, 2, 10, 11, 57, 71]]
  edges := [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10), (10, 11), (11, 12), (4, 13), (5, 13), (6, 13), (7, 13), (8, 13), (11, 13), (1, 14), (9, 14), (10, 14)]
  rank := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 11]

/-- State names for `ideal`, in index order. -/
def idealNames : List String := ["real-need", "published", "applied", "machine-check", "human-read", "terms-check", "work-sample", "panel", "level-and-band", "approval", "offer", "verification", "hired", "declined", "closed"]

/-- WF-001, the funnel as it actually runs. -/
def observed : Machine where
  n := 17
  kind := [Kind.initial, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.terminal, Kind.terminal, Kind.terminal, Kind.terminal]
  deviations := [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
  edges := [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (4, 14), (5, 6), (5, 16), (6, 7), (6, 14), (7, 8), (7, 14), (8, 9), (8, 14), (9, 10), (9, 14), (10, 11), (10, 15), (11, 12), (11, 15), (12, 13), (12, 14), (2, 16), (14, 2)]
  rank := [0, 1, 206, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 205, 204, 198]

/-- State names for `observed`, in index order. -/
def observedNames : List String := ["drafted", "authorised", "published", "received", "machine-screened", "recruiter-queue", "recruiter-screen", "technical", "panel", "levelling", "approval", "offer", "verification", "hired", "rejected", "frozen", "lapsed"]

/-- The barrier DAG, ordered by funnel position. -/
def gates : Machine where
  n := 14
  kind := [Kind.initial, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.active, Kind.terminal]
  deviations := [[], [], [], [], [], [], [], [], [], [], [], [], [], []]
  edges := [(0, 1), (0, 2), (1, 2), (1, 5), (2, 3), (3, 4), (3, 5), (4, 5), (5, 6), (6, 7), (6, 8), (7, 8), (8, 9), (9, 10), (10, 11), (11, 12), (12, 13)]
  rank := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

/-- State names for `gates`, in index order. -/
def gatesNames : List String := ["B-013", "B-014", "B-001", "B-002", "B-003", "B-004", "B-005", "B-006", "B-007", "B-008", "B-009", "B-010", "B-011", "B-012"]

/-- Every entity a state can name, in index order. -/
def entityNames : List String := ["A-001", "A-002", "A-003", "A-004", "A-005", "A-006", "A-007", "A-008", "A-009", "A-010", "A-011", "A-012", "A-013", "A-014", "A-015", "A-016", "A-017", "A-018", "B-001", "B-002", "B-003", "B-004", "B-005", "B-006", "B-007", "B-008", "B-009", "B-010", "B-011", "B-012", "B-013", "B-014", "I-001", "I-002", "I-003", "I-004", "I-005", "I-006", "I-007", "I-008", "I-009", "I-010", "I-011", "I-012", "I-013", "I-014", "I-015", "I-016", "I-017", "L-001", "L-002", "L-003", "M-001", "M-002", "M-003", "M-004", "M-005", "M-006", "M-007", "M-008", "M-009", "M-010", "M-011", "M-012", "M-013", "M-014", "M-015", "M-016", "M-017", "M-018", "M-019", "M-020", "M-021", "M-022", "M-023", "M-024", "P-001", "P-002", "P-003", "P-004"]

/-- The barriers, as indices into `entityNames`. -/
def barrierIds : List Nat := [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]

/-- The mechanisms, as indices into `entityNames`. -/
def mechanismIds : List Nat := [52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75]

/-- A closed walk found in the observed funnel: out of this state, and back. -/
def observedCycleStart : Nat := 2
def observedCycleTail : List Nat := [3, 4, 14]

end Hoba
