/**
 * Vector Cat Engine — Curated Presets & Gallery Hall of Fame
 */

import type { CatDNA } from './types.js';

export interface CatPreset {
  id: string;
  name: Record<'uk' | 'en', string>;
  title: Record<'uk' | 'en', string>;
  description: Record<'uk' | 'en', string>;
  dna: Partial<CatDNA> & { seed: string };
}

export const CAT_PRESETS: CatPreset[] = [
  {
    id: 'borys-loaf',
    name: { uk: 'Борис', en: 'Boris' },
    title: { uk: 'Професор Котобуханства', en: 'Professor of Loafing' },
    description: {
      uk: 'Еталонний теплий котобуханець із класичним рудим таббі-забарвленням та золотим дзвіночком.',
      en: 'The golden standard of warm cat loaves with classic orange tabby stripes and jingle bell collar.',
    },
    dna: {
      seed: 'borys-loaf-master',
      version: 1,
      pose: 'loaf',
      headShape: 'fluffyCheeks',
      earType: 'classic',
      eyeShape: 'animeSparkle',
      eyeColor: 'emerald',
      mouthEmotion: 'purr3',
      coatStyle: 'ginger',
      furPattern: 'tabbyStripes',
      tailType: 'fluffyPlume',
      headAccessory: 'none',
      neckAccessory: 'bellCollar',
      propItem: 'coffeeMug',
      backdropTheme: 'sparkleStars',
      whiskerLength: 1.1,
      blushIntensity: 0.7,
      chonkFactor: 1.15,
      earAngleOffset: 0,
      tailWagAngle: 0,
      furHueShift: 0,
    },
  },
  {
    id: 'merlin-wizard',
    name: { uk: 'Мерлін', en: 'Merlin' },
    title: { uk: 'Верховний Маг Теплих Батарей', en: 'Archmage of Cozy Radiators' },
    description: {
      uk: 'Містичний чорний войд у гостроверхому капелюсі чарівника із сяючими бурштиновими очима.',
      en: 'A mystical void cat in a pointy wizard hat with glowing amber eyes.',
    },
    dna: {
      seed: 'merlin-wizard-cat',
      version: 1,
      pose: 'sitting',
      headShape: 'round',
      earType: 'classic',
      eyeShape: 'animeSparkle',
      eyeColor: 'amberGold',
      mouthEmotion: 'purr3',
      coatStyle: 'voidBlack',
      furPattern: 'none',
      tailType: 'sleekWhip',
      headAccessory: 'wizardHat',
      neckAccessory: 'none',
      propItem: 'none',
      backdropTheme: 'sparkleStars',
      whiskerLength: 1.2,
      blushIntensity: 0.3,
      chonkFactor: 0.95,
      earAngleOffset: 0,
      tailWagAngle: 10,
      furHueShift: 0,
    },
  },
  {
    id: 'smetanka-crown',
    name: { uk: 'Сметанка', en: 'Smetanka' },
    title: { uk: 'Його Пухнаста Величність', en: 'His Fluffiest Majesty' },
    description: {
      uk: 'Ультра-круглий білосніжний кіт у золотій короні та елегантному червоному метелику.',
      en: 'An ultra-round snowy white royal chonk with a gold crown and dapper red bow tie.',
    },
    dna: {
      seed: 'smetanka-the-royal',
      version: 1,
      pose: 'orb',
      headShape: 'chonky',
      earType: 'roundBear',
      eyeShape: 'animeSparkle',
      eyeColor: 'sapphireDeep',
      mouthEmotion: 'purr3',
      coatStyle: 'snowWhite',
      furPattern: 'none',
      tailType: 'bobtailBun',
      headAccessory: 'royalCrown',
      neckAccessory: 'bowTie',
      propItem: 'none',
      backdropTheme: 'floatingHearts',
      whiskerLength: 0.9,
      blushIntensity: 0.8,
      chonkFactor: 1.25,
      earAngleOffset: 0,
      tailWagAngle: 0,
      furHueShift: 0,
    },
  },
  {
    id: 'cyber-meow-2077',
    name: { uk: 'Кібер-Мяу 2077', en: 'CyberMeow 2077' },
    title: { uk: 'Нейромережевий Хакер', en: 'Neural Network Hacker' },
    description: {
      uk: 'Неоновий кіт із крутими сонцезахисними окулярами та кібернетичним фоном.',
      en: 'A synthwave neon feline rocking cool shades on a matrix grid.',
    },
    dna: {
      seed: 'cyber-meow-matrix-2077',
      version: 1,
      pose: 'sitting',
      headShape: 'triangle',
      earType: 'lynx',
      eyeShape: 'slitPredator',
      eyeColor: 'cyanSky',
      mouthEmotion: 'smugSmile',
      coatStyle: 'cyberNeon',
      furPattern: 'none',
      tailType: 'zigzagKink',
      headAccessory: 'sunglasses',
      neckAccessory: 'fishbonePendant',
      propItem: 'laserDot',
      backdropTheme: 'cyberGrid',
      whiskerLength: 1.0,
      blushIntensity: 0.4,
      chonkFactor: 1.0,
      earAngleOffset: 0,
      tailWagAngle: -5,
      furHueShift: 0,
    },
  },
  {
    id: 'shkarpetik-box',
    name: { uk: 'Шкарпетик', en: 'Socks' },
    title: { uk: 'Інспектор Картонних Коробок', en: 'Cardboard Box Inspector' },
    description: {
      uk: 'Чорно-білий смокінг-кіт, який заліз у посилку з рибкою на голові та висолопленим язичком.',
      en: 'A tuxedo cat sitting snug in a box with a fish on head and tiny blep tongue.',
    },
    dna: {
      seed: 'shkarpetik-box-adventure',
      version: 1,
      pose: 'box',
      headShape: 'fluffyCheeks',
      earType: 'fold',
      eyeShape: 'wink',
      eyeColor: 'emerald',
      mouthEmotion: 'blep',
      coatStyle: 'tuxedo',
      furPattern: 'socksAndBib',
      tailType: 'curlySpiral',
      headAccessory: 'fishOnHead',
      neckAccessory: 'none',
      propItem: 'none',
      backdropTheme: 'fishPattern',
      whiskerLength: 1.1,
      blushIntensity: 0.8,
      chonkFactor: 1.05,
      earAngleOffset: 0,
      tailWagAngle: 0,
      furHueShift: 0,
    },
  },
  {
    id: 'persyk-yoga',
    name: { uk: 'Персик', en: 'Peaches' },
    title: { uk: 'Майстер Котячої Йоги', en: 'Master of Feline Yoga' },
    description: {
      uk: 'Каліко-кішка у граційній позі потягусь із зеленим паростком на маківці та вазончиком.',
      en: 'A graceful calico cat doing a deep yoga stretch with a sprout on her head.',
    },
    dna: {
      seed: 'persyk-calico-yoga',
      version: 1,
      pose: 'stretching',
      headShape: 'heart',
      earType: 'classic',
      eyeShape: 'curvedHappy',
      eyeColor: 'emerald',
      mouthEmotion: 'purr3',
      coatStyle: 'calico',
      furPattern: 'none',
      tailType: 'candyCane',
      headAccessory: 'sproutLeaf',
      neckAccessory: 'none',
      propItem: 'pottedPlant',
      backdropTheme: 'pawPrints',
      whiskerLength: 1.0,
      blushIntensity: 0.7,
      chonkFactor: 0.95,
      earAngleOffset: 0,
      tailWagAngle: 12,
      furHueShift: 0,
    },
  },
  {
    id: 'lucifer-zoomies',
    name: { uk: 'Люциферчик', en: 'Lucifer' },
    title: { uk: 'Гроза Кімнатних Квітів', en: 'Nighttime Zoomies Menace' },
    description: {
      uk: 'Грайливий чорний кіт з червоними ріжками на низькому старті перед стрибком на клубок шерсті.',
      en: 'A mischievous black kitten with cute devil horns crouched to pounce on a yarn ball.',
    },
    dna: {
      seed: 'lucifer-playful-devil',
      version: 1,
      pose: 'pounce',
      headShape: 'round',
      earType: 'classic',
      eyeShape: 'shockedRound',
      eyeColor: 'amberGold',
      mouthEmotion: 'gaspO',
      coatStyle: 'voidBlack',
      furPattern: 'none',
      tailType: 'fluffyPlume',
      headAccessory: 'devilHorns',
      neckAccessory: 'none',
      propItem: 'yarnBall',
      backdropTheme: 'glowingAura',
      whiskerLength: 1.2,
      blushIntensity: 0.5,
      chonkFactor: 1.0,
      earAngleOffset: 0,
      tailWagAngle: -15,
      furHueShift: 0,
    },
  },
  {
    id: 'vasyl-chef',
    name: { uk: 'Шеф Василь', en: 'Chef Basil' },
    title: { uk: 'Головний Дегустатор Вершків', en: 'Head Cream Sommelier' },
    description: {
      uk: 'Британський димчастий кіт у кухарському ковпаку та смугастому шарфику.',
      en: 'A smoky British blue cat wearing a tall chef hat and a cozy scarf.',
    },
    dna: {
      seed: 'vasyl-master-chef',
      version: 1,
      pose: 'loaf',
      headShape: 'chonky',
      earType: 'classic',
      eyeShape: 'sleepyLids',
      eyeColor: 'amberGold',
      mouthEmotion: 'smugSmile',
      coatStyle: 'britishBlue',
      furPattern: 'none',
      tailType: 'bobtailBun',
      headAccessory: 'chefHat',
      neckAccessory: 'warmScarf',
      propItem: 'coffeeMug',
      backdropTheme: 'cozyPillow',
      whiskerLength: 1.1,
      blushIntensity: 0.6,
      chonkFactor: 1.2,
      earAngleOffset: 0,
      tailWagAngle: 0,
      furHueShift: 0,
    },
  },
];
