/**
 * Bundles the Pages worker.
 *
 * `_worker.js` used to be a single hand-written file shipped verbatim, which
 * meant it could not import anything — so the validate endpoints would have had
 * to reimplement rules that already exist as library functions. Bundling lets
 * the worker call `@hoba/registry/edge` directly, and the output stays a single
 * committed file, so nothing about the deploy changes.
 */
import path from 'node:path';
import { build } from 'esbuild';
import { resolveRegistryRoot } from '@hoba/registry';

const root = resolveRegistryRoot();
const entry = path.join(root, 'apps', 'web', 'src', 'worker', 'index.js');
const outfile = path.join(root, 'apps', 'web', 'public', '_worker.js');

async function main() {
const result = await build({
  entryPoints: [entry],
  outfile,
  bundle: true,
  format: 'esm',
  target: 'es2022',
  platform: 'neutral',
  // Readable on purpose: this file is committed, and a diff nobody can read is
  // a diff nobody reviews.
  minify: false,
  legalComments: 'none',
  banner: {
    js: '// GENERATED by scripts/build-worker.ts from apps/web/src/worker/. Do not edit by hand.',
  },
  metafile: true,
});

  const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
  console.log(`worker: ${(bytes / 1024).toFixed(1)} kB -> ${path.relative(root, outfile)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
