/**
 * Bundles the Pages worker.
 *
 * `_worker.js` used to be a single hand-written file shipped verbatim, which
 * meant it could not import anything — so the validate endpoints would have had
 * to reimplement rules that already exist as library functions. Bundling lets
 * the worker call `@hoba/registry/edge` directly, and the output stays a single
 * committed file, so nothing about the deploy changes.
 */
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { build } from 'esbuild';
import { resolveRegistryRoot } from '@hoba/registry';

const root = resolveRegistryRoot();
const entry = path.join(root, 'apps', 'web', 'src', 'worker', 'index.js');
const outfile = path.join(root, 'apps', 'web', 'public', '_worker.js');

async function main() {
  const result = await build({
    entryPoints: [entry],
    outfile,
    bundle: true,
    format: 'esm',
    target: 'es2022',
    platform: 'neutral',
    // Readable on purpose: this file is committed, and a diff nobody can read is
    // a diff nobody reviews.
    minify: false,
    legalComments: 'none',
    banner: {
      js: '// GENERATED by scripts/build-worker.ts from apps/web/src/worker/. Do not edit by hand.',
    },
    metafile: true,
  });

  // What ships is checked, not how it was made. esbuild's `neutral` platform
  // refuses to resolve Node's built-ins today, so a barrel import that drags
  // `node:fs` in fails the build — that is where the last one was caught. But
  // that protection is a property of this config: adding `external`, or moving
  // the platform to `node`, turns the same mistake back into a bundle that
  // builds, ships, and fails only when Cloudflare runs it.
  const [, output] = Object.entries(result.metafile.outputs)[0];
  const bundled = await readFile(outfile, 'utf8');
  const reachedIn = [
    ...bundled.matchAll(/\bfrom\s*["'](node:[^"']+)["']|\brequire\(\s*["']([^"']+)["']/g),
  ].map((m) => m[1] ?? m[2]);
  if (reachedIn.length > 0) {
    throw new Error(
      `worker bundle reaches ${[...new Set(reachedIn)].join(', ')}, which the edge cannot provide.\n` +
        `Import exact modules (\`@hoba/registry/edge\`, not \`@hoba/registry\`): a package barrel\n` +
        `re-exports the filesystem loader.`
    );
  }

  console.log(`worker: ${(output.bytes / 1024).toFixed(1)} kB -> ${path.relative(root, outfile)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
